apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kalshi-postgres-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kalshi.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
  {{- if .Values.postgres.storageClass }}
  storageClassName: {{ .Values.postgres.storageClass }}
  {{- end }}
