apiVersion: v1
kind: Service
metadata:
  name: kalshi-streamlit
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kalshi.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kalshi.streamlit.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8501
      targetPort: 8501
  type: ClusterIP
